### ISSUE TITLE
NoSuchMethodError报错

### ISSUE THREAD

**Issue by xingpz2008** [Cool-Coding/remote-desktop-control#21]
Exception in thread "main" java.lang.NoSuchMethodError: io.grpc.NameResolverProvider.asFactory()Lio/grpc/NameResolver$Factory;
	at io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(AbstractManagedChannelImplBuilder.java:89)
	at cn.yang.puppet.client.PuppetStarter.ConnectGoRobotIfNecessary(PuppetStarter.java:50)
	at cn.yang.puppet.client.PuppetStarter.main(PuppetStarter.java:29)

**Comment by xingpz2008** [comment]
solved, remove io.grpc.api:1.38.0
