### ISSUE TITLE
连接不了 服务端这里运行了一会儿就自己关了

### ISSUE THREAD

**Issue by SharkPika** [Cool-Coding/remote-desktop-control#47]

**Comment by SharkPika** [comment]
024-05-26 23:18:58 191 [ main:3259]-[ ERROR ]cn.yang.server.netty.NettyServer.start(NettyServer.java:56)
Cannot assign requested address: bind
java.net.BindException: Cannot assign requested address: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:478)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1021)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:455)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:844)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:197)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:350)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-26 23:18:58 192 [ main:3260]-[ ERROR ]cn.yang.server.ServerStarter.main(ServerStarter.java:26)
Cannot assign requested address: bind

**Comment by wakingupdelta** [comment]
一样的错误，请问你是在windows环境下运行吗

**Comment by SharkPika** [comment]
> 一样的错误，请问你是在windows环境下运行吗

是的

**Comment by wakingupdelta** [comment]
我把server-config.txt中的server.ip改成127.0.0.1就可以了
